-- Etapa 39: Ciências; originais geradas com auxílio de IA, revisão humana pendente.
-- Gerado por scripts/build-subject-content.mjs. Uma instrução atômica por lote.
-- Fonte atual: revisão da etapa 41, versão 2; INSERT não atualiza linhas existentes.
-- Conflitos de ID preservam conteúdo/modelos/gabaritos; sem reparo silencioso.
with source_data (id, statement, option_a, option_b, option_c, option_d, option_e,
                  topic, difficulty, correct_answer, explanation) as (
  values
  ('d1390000-0000-4000-8000-000000000001', 'Na fotossíntese realizada por uma planta verde, qual é a principal fonte de energia usada para produzir matéria orgânica?', 'A matéria orgânica pronta das raízes', 'O calor liberado pelos animais', 'O sal da água', 'O oxigênio do solo', 'A luz do Sol', 'Fotossíntese', 'easy', 'E', 'A planta utiliza energia luminosa para produzir matéria orgânica a partir de substâncias como água e dióxido de carbono. A luz é fonte de energia, não um nutriente retirado do solo.'),
  ('d1390000-0000-4000-8000-000000000002', 'Em uma célula de folha de uma planta verde, qual organela está diretamente relacionada à realização da fotossíntese?', 'Cloroplasto', 'Núcleo', 'Lisossomo', 'Mitocôndria', 'Ribossomo', 'Cloroplastos', 'medium', 'A', 'Em plantas, a fotossíntese ocorre nos cloroplastos, que contêm pigmentos capazes de captar luz. A mitocôndria participa de processos da respiração celular.'),
  ('d1390000-0000-4000-8000-000000000003', 'Folhas caídas em uma floresta são degradadas por fungos e bactérias decompositoras. Qual é a importância desse processo para o ambiente?', 'Impedir qualquer crescimento de plantas', 'Devolver nutrientes à circulação no ecossistema', 'Transformar toda a matéria em luz', 'Eliminar definitivamente os elementos químicos', 'Parar a circulação de água', 'Decomposição', 'easy', 'B', 'A decomposição transforma a matéria orgânica e contribui para devolver nutrientes ao ambiente. Ela participa da ciclagem da matéria, sem fazer os elementos químicos desaparecerem.'),
  ('d1390000-0000-4000-8000-000000000004', 'Nas células animais, qual organela participa de etapas da respiração celular aeróbia associadas à produção de ATP?', 'Cromossomo', 'Vacúolo central vegetal', 'Mitocôndria', 'Cloroplasto', 'Parede celular', 'Respiração celular', 'medium', 'C', 'A mitocôndria participa de etapas da respiração celular aeróbia que produzem ATP, uma molécula usada nas atividades celulares. Nem todas as etapas da respiração ocorrem dentro dessa organela.'),
  ('d1390000-0000-4000-8000-000000000005', 'Uma célula precisa trocar substâncias com seu meio e controlar parte do que entra e sai. Qual estrutura atua como esse limite seletivo da célula?', 'Membrana plasmática', 'Ribossomo', 'Nucléolo', 'Cromossomo', 'Centríolo', 'Membrana celular', 'easy', 'A', 'A membrana plasmática delimita a célula e apresenta permeabilidade seletiva. Ela participa do controle das trocas de substâncias entre o interior celular e o ambiente.'),
  ('d1390000-0000-4000-8000-000000000006', 'Considere a cadeia: algas → pequenos crustáceos → peixes → garças. As setas apontam do alimento para quem o consome. Qual componente é consumidor secundário nessa cadeia?', 'Algas', 'Peixes', 'Garças', 'Pequenos crustáceos', 'Todos os componentes', 'Níveis tróficos', 'medium', 'B', 'Os crustáceos consomem as algas produtoras e são consumidores primários. Os peixes que comem esses crustáceos são consumidores secundários. As garças ocupam o nível seguinte na cadeia apresentada.'),
  ('d1390000-0000-4000-8000-000000000007', 'Uma pequena poça diminui ao longo de uma tarde sem chuva, sem escoar e sem infiltrar no solo. A água passa gradualmente para a atmosfera. Qual processo explica essa passagem?', 'Fusão', 'Precipitação', 'Condensação', 'Solidificação', 'Evaporação', 'Evaporação', 'easy', 'E', 'Na evaporação, a água líquida passa ao estado gasoso. Esse processo pode acontecer na superfície da água sem que ela esteja fervendo.'),
  ('d1390000-0000-4000-8000-000000000008', 'Gotas aparecem na parte externa de um copo fechado com água gelada, colocado em ambiente úmido. Considerando que o copo não vaza, de onde vêm essas gotas?', 'Da criação de água sem matéria anterior', 'Do vidro, que se transforma em água', 'Do sal dissolvido que sai do copo', 'Do vapor de água do ar que se condensa', 'Do gelo que atravessa o vidro', 'Condensação', 'easy', 'D', 'O vapor de água presente no ar perde energia ao entrar em contato com a superfície fria e passa ao estado líquido. Essa condensação forma as gotas externas.'),
  ('d1390000-0000-4000-8000-000000000009', 'Uma mistura contém água e areia insolúvel, cujos grãos são maiores que os poros de um filtro. Qual procedimento pode reter a areia e deixar a água atravessar?', 'Filtração', 'Dissolução completa da areia', 'Fusão do recipiente', 'Magnetização da água', 'Congelamento sem separação', 'Separação de misturas', 'easy', 'A', 'O filtro retém os grãos sólidos maiores que seus poros, enquanto a água atravessa. A filtração separa, nesse caso, um sólido insolúvel de um líquido; não torna a água necessariamente potável.'),
  ('d1390000-0000-4000-8000-000000000010', 'Uma pequena quantidade de sal se dissolve completamente em água, formando uma mistura uniforme. Nessa solução, como o sal é classificado?', 'Precipitado sólido presente', 'Filtro', 'Recipiente', 'Soluto', 'Solvente', 'Soluções', 'easy', 'D', 'O sal é o soluto, isto é, a substância dissolvida. A água atua como solvente. A dissolução completa nas condições descritas resulta em uma solução uniforme.'),
  ('d1390000-0000-4000-8000-000000000011', 'Um bloco homogêneo tem massa de 200 g e volume de 100 cm³. Usando densidade = massa ÷ volume, qual é sua densidade?', '100 g/cm³', '20 g/cm³', '0,5 g/cm³', '300 g/cm³', '2 g/cm³', 'Densidade', 'medium', 'E', 'A densidade é 200 ÷ 100 = 2 g/cm³. A unidade relaciona a massa em gramas ao volume em centímetros cúbicos.'),
  ('d1390000-0000-4000-8000-000000000012', 'Uma força resultante de 20 N atua sobre um carrinho de massa 4 kg. Usando F = m × a, qual é a aceleração do carrinho?', '5 m/s²', '16 m/s²', '80 m/s²', '0,2 m/s²', '4 m/s²', 'Força e aceleração', 'medium', 'A', 'Pela relação fornecida, a = F ÷ m = 20 ÷ 4 = 5 m/s². O valor usado é o da força resultante, que já reúne as forças que atuam no carrinho.'),
  ('d1390000-0000-4000-8000-000000000013', 'Um veículo percorre 24 km em 2 horas. Qual é sua velocidade média, considerando todo esse intervalo?', '48 km/h', '22 km/h', '6 km/h', '12 km/h', '26 km/h', 'Velocidade média', 'medium', 'D', 'A velocidade média é a distância percorrida dividida pelo tempo total: 24 ÷ 2 = 12 km/h. Isso não exige que a velocidade tenha sido constante durante o percurso.'),
  ('d1390000-0000-4000-8000-000000000014', 'Uma ponta de uma colher de metal fica em contato com um líquido quente. Depois de algum tempo, a outra ponta também aquece. Qual mecanismo explica principalmente a transferência de energia ao longo do metal?', 'Convecção térmica', 'Condução térmica', 'Radiação térmica', 'Dilatação térmica', 'Evaporação do líquido', 'Condução térmica', 'medium', 'B', 'A condução transfere energia térmica através do material, da região mais quente para a mais fria, sem exigir deslocamento do metal como um todo.'),
  ('d1390000-0000-4000-8000-000000000015', 'Um circuito simples tem pilha carregada, fios, lâmpada compatível e interruptor, todos em bom estado. O interruptor aberto interrompe o caminho elétrico. O que deve ocorrer para a lâmpada acender nesse circuito?', 'Cortar outro fio', 'Separar os dois terminais da lâmpada dos fios', 'Retirar a pilha', 'Retirar a lâmpada do circuito', 'Fechar o interruptor e completar o caminho elétrico', 'Circuito elétrico simples', 'medium', 'E', 'Um caminho elétrico completo permite a circulação de corrente no circuito descrito. Fechar o interruptor restabelece esse caminho; abrir ou cortar conexões o interrompe.'),
  ('d1390000-0000-4000-8000-000000000016', 'Ao observar a Lua iluminada no céu, qual é a principal origem da luz que vemos em sua superfície?', 'Luz produzida pela sombra da Terra', 'Luz produzida por combustão na Lua', 'Luz gerada pelo som na atmosfera terrestre', 'Luz do Sol refletida pela Lua', 'Luz emitida por oceanos lunares', 'Luz da Lua', 'easy', 'D', 'A Lua não produz luz visível como uma estrela. Sua superfície reflete parte da luz solar, e a porção iluminada que observamos varia conforme a posição relativa entre Sol, Terra e Lua.'),
  ('d1390000-0000-4000-8000-000000000017', 'Qual combinação explica principalmente as estações do ano na Terra?', 'As fases da Lua e a duração do ciclo lunar', 'A variação da distância entre a Terra e o Sol ao longo da órbita', 'A inclinação do eixo terrestre e a translação ao redor do Sol', 'A variação da atividade solar ao longo de seu ciclo', 'A rotação da Terra ao longo de cada dia', 'Estações do ano', 'medium', 'C', 'Com o eixo inclinado, a translação faz variar a incidência de luz e a duração dos dias em cada hemisfério ao longo do ano. A causa principal não é simplesmente a Terra estar mais perto ou mais longe do Sol.'),
  ('d1390000-0000-4000-8000-000000000018', 'Uma turma quer investigar o efeito da quantidade de água no crescimento de plantas. Usa plantas semelhantes, vasos e solo iguais. Qual planejamento permite comparar principalmente o efeito da água?', 'Variar água, luz e tipo de solo ao mesmo tempo', 'Trocar a espécie de planta em cada quantidade de água', 'Mudar o solo e manter a quantidade de água igual', 'Colocar cada vaso em uma temperatura diferente', 'Variar a água e manter semelhantes as demais condições', 'Controle de variáveis', 'medium', 'E', 'Variar a quantidade de água e manter as demais condições semelhantes reduz a influência de outros fatores na comparação. Repetições e registros também ajudam; um único resultado não prova uma regra universal.')
), inserted_model as (
  insert into private.simulations(id,title,question_count,subject,published,free_access)
  values('d1391000-0000-4000-8000-000000000001','Ciências',20,'ciencias',false,false)
  on conflict(id) do nothing returning id
), inserted_questions as (
  insert into public.questions(id,statement,option_a,option_b,option_c,option_d,option_e,
                               subject,topic,difficulty,target_exam,status,version)
  select id::uuid,statement,option_a,option_b,option_c,option_d,option_e,
         'ciencias',topic,difficulty,'both','draft',2 from source_data
  on conflict(id) do nothing returning id
)
insert into public.question_answers(question_id,correct_answer,explanation)
select q.id,s.correct_answer,s.explanation
from inserted_questions q join source_data s on s.id::uuid=q.id;
