-- Três lotes. Envolver em BEGIN/COMMIT para carga conjunta atômica.
-- Etapa 39: Ciências; originais geradas com auxílio de IA, revisão humana pendente.
-- Gerado por scripts/build-subject-content.mjs. Uma instrução atômica por lote.
-- Conflitos de ID preservam conteúdo/modelos/gabaritos; sem reparo silencioso.
with source_data (id, statement, option_a, option_b, option_c, option_d, option_e,
                  topic, difficulty, correct_answer, explanation) as (
  values
  ('d1390000-0000-4000-8000-000000000001', 'Na fotossíntese realizada por uma planta verde, qual é a principal fonte de energia usada para produzir matéria orgânica?', 'A luz do Sol', 'O oxigênio do solo', 'O calor liberado pelos animais', 'O sal da água', 'A matéria orgânica pronta das raízes', 'Fotossíntese', 'easy', 'A', 'A planta utiliza energia luminosa para produzir matéria orgânica a partir de substâncias como água e dióxido de carbono. A luz é fonte de energia, não um nutriente retirado do solo.'),
  ('d1390000-0000-4000-8000-000000000002', 'Em uma célula de folha de uma planta verde, qual organela está diretamente relacionada à realização da fotossíntese?', 'Lisossomo', 'Mitocôndria', 'Ribossomo', 'Cloroplasto', 'Núcleo', 'Cloroplastos', 'medium', 'D', 'Em plantas, a fotossíntese ocorre nos cloroplastos, que contêm pigmentos capazes de captar luz. A mitocôndria participa de processos da respiração celular.'),
  ('d1390000-0000-4000-8000-000000000003', 'Folhas caídas em uma floresta são degradadas por fungos e bactérias decompositoras. Qual é a importância desse processo para o ambiente?', 'Eliminar definitivamente os elementos químicos', 'Devolver nutrientes à circulação no ecossistema', 'Impedir qualquer crescimento de plantas', 'Transformar toda a matéria em luz', 'Parar a circulação de água', 'Decomposição', 'easy', 'B', 'A decomposição transforma a matéria orgânica e contribui para devolver nutrientes ao ambiente. Ela participa da ciclagem da matéria, sem fazer os elementos químicos desaparecerem.'),
  ('d1390000-0000-4000-8000-000000000004', 'Nas células animais, qual organela participa de etapas da respiração celular aeróbia associadas à produção de ATP?', 'Cloroplasto', 'Parede celular', 'Vacúolo central vegetal', 'Cromossomo', 'Mitocôndria', 'Respiração celular', 'medium', 'E', 'A mitocôndria participa de etapas da respiração celular aeróbia que produzem ATP, uma molécula usada nas atividades celulares. Nem todas as etapas da respiração ocorrem dentro dessa organela.'),
  ('d1390000-0000-4000-8000-000000000005', 'Uma célula precisa trocar substâncias com seu meio e controlar parte do que entra e sai. Qual estrutura atua como esse limite seletivo da célula?', 'Cromossomo', 'Ribossomo', 'Membrana plasmática', 'Nucléolo', 'Centríolo', 'Membrana celular', 'easy', 'C', 'A membrana plasmática delimita a célula e apresenta permeabilidade seletiva. Ela participa do controle das trocas de substâncias entre o interior celular e o ambiente.'),
  ('d1390000-0000-4000-8000-000000000006', 'Considere a cadeia: algas → pequenos crustáceos → peixes → garças. As setas apontam do alimento para quem o consome. Qual componente é consumidor secundário nessa cadeia?', 'Peixes', 'Algas', 'Garças', 'Pequenos crustáceos', 'Todos os componentes', 'Níveis tróficos', 'medium', 'A', 'Os crustáceos consomem as algas produtoras e são consumidores primários. Os peixes que comem esses crustáceos são consumidores secundários. As garças ocupam o nível seguinte na cadeia apresentada.'),
  ('d1390000-0000-4000-8000-000000000007', 'Uma pequena poça diminui ao longo de uma tarde sem chuva, sem escoar e sem infiltrar no solo. A água passa gradualmente para a atmosfera. Qual processo explica essa passagem?', 'Solidificação', 'Fusão', 'Condensação', 'Evaporação', 'Precipitação', 'Evaporação', 'easy', 'D', 'Na evaporação, a água líquida passa ao estado gasoso. Esse processo pode acontecer na superfície da água sem que ela esteja fervendo.'),
  ('d1390000-0000-4000-8000-000000000008', 'Gotas aparecem na parte externa de um copo fechado com água gelada, colocado em ambiente úmido. Considerando que o copo não vaza, de onde vêm essas gotas?', 'Do vidro, que se transforma em água', 'Do vapor de água do ar que se condensa', 'Do gelo que atravessa o vidro', 'Da criação de água sem matéria anterior', 'Do sal dissolvido que sai do copo', 'Condensação', 'easy', 'B', 'O vapor de água presente no ar perde energia ao entrar em contato com a superfície fria e passa ao estado líquido. Essa condensação forma as gotas externas.'),
  ('d1390000-0000-4000-8000-000000000009', 'Uma mistura contém água e areia insolúvel, cujos grãos são maiores que os poros de um filtro. Qual procedimento pode reter a areia e deixar a água atravessar?', 'Dissolução completa da areia', 'Fusão do recipiente', 'Magnetização da água', 'Congelamento sem separação', 'Filtração', 'Separação de misturas', 'easy', 'E', 'O filtro retém os grãos sólidos maiores que seus poros, enquanto a água atravessa. A filtração separa, nesse caso, um sólido insolúvel de um líquido; não torna a água necessariamente potável.'),
  ('d1390000-0000-4000-8000-000000000010', 'Uma pequena quantidade de sal se dissolve completamente em água, formando uma mistura uniforme. Nessa solução, como o sal é classificado?', 'Solvente', 'Filtro', 'Soluto', 'Precipitado sólido presente', 'Recipiente', 'Soluções', 'easy', 'C', 'O sal é o soluto, isto é, a substância dissolvida. A água atua como solvente. A dissolução completa nas condições descritas resulta em uma solução uniforme.'),
  ('d1390000-0000-4000-8000-000000000011', 'Um bloco homogêneo tem massa de 200 g e volume de 100 cm³. Usando densidade = massa ÷ volume, qual é sua densidade?', '2 g/cm³', '0,5 g/cm³', '20 g/cm³', '100 g/cm³', '300 g/cm³', 'Densidade', 'medium', 'A', 'A densidade é 200 ÷ 100 = 2 g/cm³. A unidade relaciona a massa em gramas ao volume em centímetros cúbicos.'),
  ('d1390000-0000-4000-8000-000000000012', 'Uma força resultante de 20 N atua sobre um carrinho de massa 4 kg. Usando F = m × a, qual é a aceleração do carrinho?', '80 m/s²', '16 m/s²', '4 m/s²', '5 m/s²', '0,2 m/s²', 'Força e aceleração', 'medium', 'D', 'Pela relação fornecida, a = F ÷ m = 20 ÷ 4 = 5 m/s². O valor usado é o da força resultante, que já reúne as forças que atuam no carrinho.'),
  ('d1390000-0000-4000-8000-000000000013', 'Um veículo percorre 24 km em 2 horas. Qual é sua velocidade média, considerando todo esse intervalo?', '48 km/h', '12 km/h', '26 km/h', '22 km/h', '6 km/h', 'Velocidade média', 'medium', 'B', 'A velocidade média é a distância percorrida dividida pelo tempo total: 24 ÷ 2 = 12 km/h. Isso não exige que a velocidade tenha sido constante durante o percurso.'),
  ('d1390000-0000-4000-8000-000000000014', 'Uma ponta de uma colher de metal fica em contato com um líquido quente. Depois de algum tempo, a outra ponta também aquece. Qual mecanismo explica principalmente a transferência de energia ao longo do metal?', 'Evaporação do metal', 'Fotossíntese', 'Solidificação do ar', 'Convecção do metal sólido', 'Condução térmica', 'Condução térmica', 'medium', 'E', 'A condução transfere energia térmica através do material, da região mais quente para a mais fria, sem exigir deslocamento do metal como um todo.'),
  ('d1390000-0000-4000-8000-000000000015', 'Um circuito simples tem pilha carregada, fios, lâmpada compatível e interruptor, todos em bom estado. O interruptor aberto interrompe o caminho elétrico. O que deve ocorrer para a lâmpada acender nesse circuito?', 'Retirar a pilha', 'Cortar outro fio', 'Fechar o interruptor e completar o caminho elétrico', 'Separar os dois terminais da lâmpada dos fios', 'Retirar a lâmpada do circuito', 'Circuito elétrico simples', 'medium', 'C', 'Um caminho elétrico completo permite a circulação de corrente no circuito descrito. Fechar o interruptor restabelece esse caminho; abrir ou cortar conexões o interrompe.'),
  ('d1390000-0000-4000-8000-000000000016', 'Ao observar a Lua iluminada no céu, qual é a principal origem da luz que vemos em sua superfície?', 'Luz do Sol refletida pela Lua', 'Luz produzida por combustão na Lua', 'Luz emitida por oceanos lunares', 'Luz gerada pelo som na atmosfera terrestre', 'Luz produzida pela sombra da Terra', 'Luz da Lua', 'easy', 'A', 'A Lua não produz luz visível como uma estrela. Sua superfície reflete parte da luz solar, e a porção iluminada que observamos varia conforme a posição relativa entre Sol, Terra e Lua.'),
  ('d1390000-0000-4000-8000-000000000017', 'Qual combinação explica principalmente as estações do ano na Terra?', 'A Lua produzir calor e a Terra parar de girar', 'O Sol ficar apagado durante metade do ano', 'A mudança diária de distância entre cidades', 'A inclinação do eixo terrestre e a translação ao redor do Sol', 'A existência de nuvens apenas no inverno', 'Estações do ano', 'medium', 'D', 'Com o eixo inclinado, a translação faz variar a incidência de luz e a duração dos dias em cada hemisfério ao longo do ano. A causa principal não é simplesmente a Terra estar mais perto ou mais longe do Sol.'),
  ('d1390000-0000-4000-8000-000000000018', 'Uma turma quer investigar o efeito da quantidade de água no crescimento de plantas. Usa plantas semelhantes, vasos e solo iguais. Qual planejamento permite comparar principalmente o efeito da água?', 'Variar água, luz e tipo de solo ao mesmo tempo', 'Variar a água e manter semelhantes as demais condições', 'Trocar a espécie de planta em cada quantidade de água', 'Colocar cada vaso em uma temperatura diferente', 'Mudar o solo e manter a quantidade de água igual', 'Controle de variáveis', 'medium', 'B', 'Variar a quantidade de água e manter as demais condições semelhantes reduz a influência de outros fatores na comparação. Repetições e registros também ajudam; um único resultado não prova uma regra universal.')
), inserted_model as (
  insert into private.simulations(id,title,question_count,subject,published,free_access)
  values('d1391000-0000-4000-8000-000000000001','Ciências',20,'ciencias',false,false)
  on conflict(id) do nothing returning id
), inserted_questions as (
  insert into public.questions(id,statement,option_a,option_b,option_c,option_d,option_e,
                               subject,topic,difficulty,target_exam,status,version)
  select id::uuid,statement,option_a,option_b,option_c,option_d,option_e,
         'ciencias',topic,difficulty,'both','draft',1 from source_data
  on conflict(id) do nothing returning id
)
insert into public.question_answers(question_id,correct_answer,explanation)
select q.id,s.correct_answer,s.explanation
from inserted_questions q join source_data s on s.id::uuid=q.id;

-- Etapa 39: História; originais geradas com auxílio de IA, revisão humana pendente.
-- Gerado por scripts/build-subject-content.mjs. Uma instrução atômica por lote.
-- Conflitos de ID preservam conteúdo/modelos/gabaritos; sem reparo silencioso.
with source_data (id, statement, option_a, option_b, option_c, option_d, option_e,
                  topic, difficulty, correct_answer, explanation) as (
  values
  ('d1392000-0000-4000-8000-000000000001', 'Em uma pesquisa sobre a história de um bairro, estudantes gravam entrevistas com antigos moradores. Que tipo de fonte é produzido principalmente por essas entrevistas?', 'Fonte cartográfica', 'Fonte oral', 'Fonte arqueológica sem linguagem', 'Fonte mineral', 'Fonte exclusivamente numérica', 'Fontes orais', 'easy', 'B', 'Entrevistas registram relatos falados e constituem fontes orais. Esses relatos apresentam memórias e perspectivas que devem ser contextualizadas e comparadas com outros registros.'),
  ('d1392000-0000-4000-8000-000000000002', 'Em um exercício hipotético, uma fotografia de uma praça mostra poucas pessoas em certo instante de 1930. Qual conclusão é adequada para uma análise histórica dessa imagem?', 'Ninguém morava na cidade naquele ano.', 'Todas as praças do país eram iguais.', 'A fotografia registra todos os acontecimentos de 1930.', 'A imagem mostra um recorte que deve ser relacionado a outras fontes.', 'Nenhuma fotografia pode ser usada como fonte.', 'Leitura de fotografias', 'medium', 'D', 'Uma fotografia registra um recorte de tempo e espaço, com enquadramento e condições de produção. Ela é uma fonte útil, mas não representa automaticamente toda a cidade ou todo o ano.'),
  ('d1392000-0000-4000-8000-000000000003', 'Dois jornais de uma mesma época descrevem um conflito de maneiras diferentes. Qual procedimento ajuda a investigar historicamente essa diferença?', 'Aceitar sempre o jornal com mais páginas.', 'Descartar ambos apenas por discordarem.', 'Examinar autoria, público, contexto e outras evidências.', 'Escolher a versão mais agradável ao pesquisador.', 'Supor que nenhum jornal tem posição editorial.', 'Crítica das fontes', 'medium', 'C', 'A análise considera quem produziu cada relato, para qual público e em quais circunstâncias, além da comparação com outras fontes. A discordância pode revelar perspectivas e interesses distintos.'),
  ('d1392000-0000-4000-8000-000000000004', 'Na contagem convencional dos séculos da era comum, a que século pertence o ano de 1750?', 'Século XVIII', 'Século XVII', 'Século XVI', 'Século XIX', 'Século XX', 'Séculos', 'easy', 'A', 'O século XVIII corresponde aos anos de 1701 a 1800. Como 1750 está nesse intervalo, pertence ao século XVIII.'),
  ('d1392000-0000-4000-8000-000000000005', 'Considere os marcos e anos: I. Proclamação da República, 1889. II. Abertura dos portos às nações amigas, 1808. III. Lei Áurea, 1888. Qual ordem apresenta os marcos do mais antigo ao mais recente?', 'I – II – III', 'III – I – II', 'II – I – III', 'I – III – II', 'II – III – I', 'Ordenação cronológica', 'easy', 'E', 'Ordenando os anos em ordem crescente, temos 1808, 1888 e 1889. Portanto, a sequência é abertura dos portos, Lei Áurea e Proclamação da República: II, III e I.'),
  ('d1392000-0000-4000-8000-000000000006', 'A abertura dos portos às nações amigas, em 1808, alterou uma regra importante do comércio colonial. Qual mudança está relacionada a essa medida?', 'Proibição de qualquer comércio marítimo.', 'Permissão de comércio com nações amigas de Portugal.', 'Abolição imediata da escravidão em todo o Brasil.', 'Criação da República brasileira.', 'Proibição de entrada da corte portuguesa no Brasil.', 'Abertura dos portos', 'medium', 'B', 'A medida permitiu comércio com nações amigas de Portugal e rompeu a exclusividade comercial metropolitana. Não significou abolição da escravidão ou implantação de uma república.'),
  ('d1392000-0000-4000-8000-000000000007', 'Qual acontecimento ajuda a explicar o contexto da transferência da corte portuguesa para o Brasil em 1808?', 'A construção de Brasília.', 'A Proclamação da República no Brasil.', 'O fim da Segunda Guerra Mundial.', 'As guerras napoleônicas e a invasão de Portugal.', 'A assinatura da Lei Áurea.', 'Transferência da corte', 'medium', 'D', 'A ameaça e a invasão de Portugal no contexto das guerras napoleônicas contribuíram para a transferência da corte. Os demais acontecimentos pertencem a períodos posteriores.'),
  ('d1392000-0000-4000-8000-000000000008', 'Qual foi a determinação central da Lei Áurea, de 13 de maio de 1888?', 'Criar o regime republicano.', 'Instituir o voto universal.', 'Extinguir legalmente a escravidão no Brasil.', 'Proibir a entrada de qualquer mercadoria estrangeira.', 'Transferir a capital para Brasília.', 'Abolição legal da escravidão', 'easy', 'C', 'A Lei Áurea determinou a extinção da escravidão no Brasil. Esse conteúdo legal não deve ser confundido com a eliminação imediata de todas as desigualdades ou com a criação da República.'),
  ('d1392000-0000-4000-8000-000000000009', 'A Lei do Ventre Livre, de 1871, declarou de condição livre os filhos de mulheres escravizadas nascidos a partir de sua data. Qual afirmação interpreta essa medida sem ampliar indevidamente seu alcance?', 'A regra sobre os nascimentos não libertava automaticamente todas as pessoas adultas escravizadas.', 'Toda a escravidão brasileira terminou imediatamente em 1871.', 'A lei criou a República brasileira.', 'A lei passou a proibir todos os nascimentos no país.', 'A medida concedeu terra a toda pessoa nascida antes de 1871.', 'Lei do Ventre Livre', 'medium', 'A', 'A disposição sobre os filhos nascidos a partir da lei não equivalia à abolição geral. A própria lei estabelecia condições de criação e de utilização de serviços desses menores, limitando a liberdade prática.'),
  ('d1392000-0000-4000-8000-000000000010', 'Qual transformação política está associada à Proclamação da República no Brasil, em 15 de novembro de 1889?', 'Retorno do Brasil à condição de colônia portuguesa.', 'Criação do primeiro governo monárquico brasileiro.', 'Abolição da escravidão pela Lei do Ventre Livre.', 'Transferência da corte portuguesa para o Brasil.', 'Fim da monarquia e implantação de um regime republicano.', 'Proclamação da República', 'easy', 'E', 'A Proclamação da República encerrou a monarquia e foi seguida por um governo provisório republicano. Essa mudança de regime não significou participação eleitoral de toda a população.'),
  ('d1392000-0000-4000-8000-000000000011', 'Segundo o artigo 70 da Constituição brasileira de 1891, os analfabetos não podiam se alistar como eleitores. O que essa restrição permite concluir sobre aquele sistema eleitoral?', 'Todos os habitantes tinham acesso ao voto.', 'A participação eleitoral possuía exclusões legais.', 'Somente crianças eram eleitores.', 'Não existia qualquer regra de alistamento.', 'A restrição referia-se apenas a visitantes estrangeiros.', 'Limites do voto em 1891', 'medium', 'B', 'A exclusão dos analfabetos mostra que a participação eleitoral não abrangia toda a população. A questão trata da regra histórica de 1891, e não das regras eleitorais atuais.'),
  ('d1392000-0000-4000-8000-000000000012', 'Nos artigos iniciais da Constituição de 1891, as antigas províncias passam a formar estados unidos em uma República Federativa. Que organização política está indicada nessa estrutura?', 'A extinção de qualquer governo nacional.', 'A transformação de cada estado em colônia estrangeira.', 'A criação de uma única cidade sem divisões territoriais.', 'A união de estados em uma federação.', 'O retorno ao regime de capitanias hereditárias.', 'Federalismo na Constituição de 1891', 'medium', 'D', 'A federação reúne estados em uma organização nacional. Os artigos 1º e 2º da Constituição de 1891 expressam a união e a transformação das antigas províncias em estados.'),
  ('d1392000-0000-4000-8000-000000000013', 'No contexto da Revolução Francesa, o artigo 1º da Declaração dos Direitos do Homem e do Cidadão, de 1789, apresenta qual princípio?', 'Privilégios jurídicos determinados exclusivamente pelo nascimento.', 'Submissão de todo cidadão a um senhor feudal.', 'Liberdade e igualdade em direitos.', 'Proibição de expressar qualquer opinião.', 'Obrigatoriedade de uma única profissão para todos.', 'Declaração de direitos de 1789', 'medium', 'C', 'O artigo afirma a liberdade e a igualdade em direitos. Enunciar esse princípio não comprova que ele tenha sido aplicado imediatamente a todas as pessoas ou em todas as situações.'),
  ('d1392000-0000-4000-8000-000000000014', 'Uma tabuleta cuneiforme da antiga Mesopotâmia registra a distribuição de utensílios de cobre. O que esse uso da escrita permite compreender?', 'A escrita também podia registrar a circulação e a administração de bens.', 'A escrita servia exclusivamente para poesias.', 'Não existia qualquer controle de bens.', 'Utensílios de cobre eram inventados no século XX.', 'Todos os habitantes sabiam ler necessariamente.', 'Escrita e administração na Mesopotâmia', 'medium', 'A', 'Registros de distribuição de bens mostram usos administrativos e econômicos da escrita. A existência de uma tabuleta não implica alfabetização de toda a população.'),
  ('d1392000-0000-4000-8000-000000000015', 'Em um exemplo didático de organização fabril, um grupo corta o tecido, outro costura e um terceiro embala as peças. Qual característica da produção é descrita?', 'Ausência de qualquer organização do trabalho.', 'Produção de alimentos por coleta silvestre.', 'Fim de todas as etapas de fabricação.', 'Cada trabalhador produz sozinho todas as peças do início ao fim.', 'Divisão de tarefas entre trabalhadores.', 'Divisão de tarefas na produção', 'easy', 'E', 'As etapas são distribuídas entre grupos, caracterizando divisão de tarefas. O exemplo não afirma que toda fábrica tenha exatamente essa organização ou que cada trabalhador realize o processo completo.'),
  ('d1392000-0000-4000-8000-000000000016', 'Ao estudar a história dos povos indígenas no Brasil, qual abordagem evita tratá-los como um único grupo cultural?', 'Afirmar que todos sempre falaram a mesma língua.', 'Reconhecer diferentes povos, línguas e formas de organização.', 'Negar a existência de mudanças históricas entre esses povos.', 'Considerar que suas histórias começaram apenas com registros europeus.', 'Supor que todos vivem de modo idêntico em qualquer lugar.', 'Diversidade dos povos indígenas', 'easy', 'B', 'Existem diversos povos indígenas, com línguas, trajetórias e formas de organização próprias. Estudar essa diversidade evita generalizações e reconhece seus sujeitos e processos históricos.'),
  ('d1392000-0000-4000-8000-000000000017', 'Em uma comparação hipotética, fotografias de 1950 e 2020 mostram a mesma estação ferroviária: o edifício permanece, mas a praça ao redor passou a ter novas vias. Qual leitura histórica considera as duas observações?', 'Nada mudou entre as duas datas.', 'Nenhum elemento permaneceu.', 'A imagem de 2020 prova como a praça era em todos os séculos.', 'Há permanência do edifício e transformação de parte de seu entorno.', 'As fotografias demonstram que os dois anos são o mesmo momento.', 'Mudanças e permanências', 'medium', 'D', 'A comparação identifica um elemento que permanece e outro que se transforma. Mudanças e permanências podem coexistir; os registros não mostram todos os acontecimentos do intervalo.'),
  ('d1392000-0000-4000-8000-000000000018', 'Qual exemplo se relaciona principalmente à dimensão imaterial do patrimônio cultural?', 'O concreto de uma ponte.', 'As paredes físicas de um edifício.', 'Saberes e modos de fazer transmitidos por uma comunidade.', 'Um terreno considerado apenas por sua área em metros quadrados.', 'A massa de uma pedra sem relação com uma prática cultural.', 'Patrimônio cultural imaterial', 'medium', 'C', 'Saberes, modos de fazer e práticas transmitidas por comunidades integram a dimensão imaterial do patrimônio. Isso não significa que toda prática esteja automaticamente registrada como bem cultural oficial.')
), inserted_model as (
  insert into private.simulations(id,title,question_count,subject,published,free_access)
  values('d1393000-0000-4000-8000-000000000001','História',20,'historia',false,false)
  on conflict(id) do nothing returning id
), inserted_questions as (
  insert into public.questions(id,statement,option_a,option_b,option_c,option_d,option_e,
                               subject,topic,difficulty,target_exam,status,version)
  select id::uuid,statement,option_a,option_b,option_c,option_d,option_e,
         'historia',topic,difficulty,'both','draft',1 from source_data
  on conflict(id) do nothing returning id
)
insert into public.question_answers(question_id,correct_answer,explanation)
select q.id,s.correct_answer,s.explanation
from inserted_questions q join source_data s on s.id::uuid=q.id;

-- Etapa 39: Geografia; originais geradas com auxílio de IA, revisão humana pendente.
-- Gerado por scripts/build-subject-content.mjs. Uma instrução atômica por lote.
-- Conflitos de ID preservam conteúdo/modelos/gabaritos; sem reparo silencioso.
with source_data (id, statement, option_a, option_b, option_c, option_d, option_e,
                  topic, difficulty, correct_answer, explanation) as (
  values
  ('d1394000-0000-4000-8000-000000000001', 'Um ponto está localizado a 15° de latitude sul e 45° de longitude oeste. Em quais hemisférios ele se encontra?', 'Norte e Leste', 'Sul e Leste', 'Sul e Oeste', 'Norte e Oeste', 'Norte e Sul simultaneamente', 'Coordenadas e hemisférios', 'easy', 'C', 'A latitude sul indica posição ao sul da linha do Equador. A longitude oeste indica posição a oeste do meridiano de Greenwich. Portanto, o ponto fica nos hemisférios Sul e Oeste.'),
  ('d1394000-0000-4000-8000-000000000002', 'No sistema usual de coordenadas geográficas, as longitudes são medidas para leste ou oeste a partir de qual referência de 0°?', 'Trópico de Câncer', 'Círculo Polar Antártico', 'Trópico de Capricórnio', 'Linha do Equador', 'Meridiano de Greenwich', 'Meridiano de referência', 'easy', 'E', 'O meridiano de Greenwich é a referência de longitude 0°. A linha do Equador é a referência para latitude, e não para longitude.'),
  ('d1394000-0000-4000-8000-000000000003', 'Em um modelo simplificado de fusos horários, cada 15° de longitude corresponde a uma hora, com horários mais adiantados a leste. Se são 10h no meridiano de 0°, que horas são no meridiano de 30° leste nesse modelo?', '12h', '8h', '10h', '11h', '14h', 'Fusos teóricos', 'medium', 'A', 'A diferença é de 30 ÷ 15 = 2 horas. Como o ponto está a leste, somam-se duas horas: 12h. O exercício usa fusos teóricos, sem fronteiras oficiais ou horário de verão.'),
  ('d1394000-0000-4000-8000-000000000004', 'Em um mapa fictício de uso do solo, a legenda indica verde para floresta, amarelo para agricultura e cinza para área construída. O que representa uma área amarela nesse mapa?', 'Floresta', 'Área construída', 'Um rio necessariamente', 'Agricultura', 'Uma fronteira internacional necessariamente', 'Legenda cartográfica', 'easy', 'D', 'A legenda fornecida associa amarelo à agricultura. Cores e símbolos precisam ser interpretados pela legenda do mapa específico, sem supor que tenham sempre o mesmo significado em todos os mapas.'),
  ('d1394000-0000-4000-8000-000000000005', 'Um mapa representa curvas de nível, cada uma ligando pontos de mesma altitude, com intervalo de 20 m entre curvas consecutivas. Na mesma escala, em qual trecho a encosta tende a ser mais íngreme?', 'Onde as curvas estão mais afastadas.', 'Onde as curvas estão mais próximas.', 'Onde não existe mudança de altitude.', 'Onde todas as curvas têm exatamente a mesma altitude.', 'Em qualquer trecho, pois a distância entre as curvas não importa.', 'Curvas de nível', 'medium', 'B', 'Com intervalo de altitude e escala iguais, curvas próximas indicam a mesma variação vertical em menor distância horizontal. Isso corresponde a maior declividade da encosta.'),
  ('d1394000-0000-4000-8000-000000000006', 'Em um mapa de escala 1:50.000, a distância em linha reta entre dois pontos mede 4 cm. Qual é a distância real correspondente?', '20 km', '200 km', '2 km', '200 m', '20 m', 'Escala e conversão de distância', 'medium', 'C', 'A distância real é 4 × 50.000 = 200.000 cm. Como 100.000 cm correspondem a 1 km, o resultado é 2 km.'),
  ('d1394000-0000-4000-8000-000000000007', 'Um município fictício tem 90.000 habitantes distribuídos em uma área de 300 km². Usando densidade demográfica = população ÷ área, qual é sua densidade média?', '30 hab./km²', '3 hab./km²', '900 hab./km²', '3.000 hab./km²', '300 hab./km²', 'Densidade demográfica', 'medium', 'E', 'Dividindo 90.000 habitantes por 300 km², obtemos 300 hab./km². É uma média do território e não significa que cada quilômetro quadrado tenha exatamente esse número de moradores.'),
  ('d1394000-0000-4000-8000-000000000008', 'Em uma região fictícia, a proporção da população residente em áreas urbanas passou de 60% para 80% entre duas pesquisas. Qual foi o aumento, em pontos percentuais?', '20 pontos percentuais', '80 pontos percentuais', '60 pontos percentuais', '33 pontos percentuais', '140 pontos percentuais', 'Proporção da população urbana', 'medium', 'A', 'A diferença entre as proporções é 80 − 60 = 20 pontos percentuais. Esse indicador não é o mesmo que o aumento percentual relativo de aproximadamente 33,3% sobre o valor inicial.'),
  ('d1394000-0000-4000-8000-000000000009', 'Uma família muda permanentemente de uma área rural para uma cidade em busca de trabalho. Qual tipo de deslocamento está exemplificado?', 'Turismo de férias', 'Migração pendular diária', 'Viagem de retorno no mesmo dia', 'Êxodo rural', 'Deslocamento de um bairro urbano para outro', 'Êxodo rural', 'easy', 'D', 'O êxodo rural é o deslocamento de pessoas do campo para a cidade. No exemplo, há mudança de residência, e não apenas uma viagem diária ou temporária.'),
  ('d1394000-0000-4000-8000-000000000010', 'Uma pessoa mora em um município, vai diariamente a outro para trabalhar e retorna à sua residência ao fim do dia. Como esse movimento é geralmente denominado?', 'Mudança definitiva de país', 'Deslocamento pendular', 'Êxodo rural necessariamente', 'Emigração permanente', 'Turismo internacional', 'Deslocamento pendular', 'easy', 'B', 'O deslocamento pendular envolve trajetos regulares de ida e volta, como os realizados para trabalhar ou estudar. A pessoa mantém sua residência, sem mudança definitiva no exemplo.'),
  ('d1394000-0000-4000-8000-000000000011', 'Uma indústria transforma algodão em tecido. Na divisão tradicional da economia em setores primário, secundário e terciário, essa atividade industrial pertence a qual setor?', 'Primário, por envolver qualquer produto de origem vegetal.', 'Terciário, por ser necessariamente comércio varejista.', 'Secundário, por transformar matéria-prima.', 'Primário, por extrair tecido pronto da natureza.', 'Terciário, por prestar exclusivamente serviços de transporte.', 'Setores da economia', 'easy', 'C', 'A transformação industrial da matéria-prima em tecido pertence ao setor secundário. O cultivo do algodão pertence ao primário; a venda e o transporte são exemplos de atividades do terciário.'),
  ('d1394000-0000-4000-8000-000000000012', 'Uma área de solo exposto e vegetação é coberta por asfalto impermeável. Mantidas as demais condições, qual efeito tende a ocorrer durante uma chuva?', 'A água passa a infiltrar mais facilmente pelo asfalto.', 'Toda a água deixa de circular no ambiente.', 'A chuva se transforma diretamente em neve.', 'A água desaparece sem escoar ou evaporar.', 'A infiltração no trecho diminui e o escoamento superficial tende a aumentar.', 'Impermeabilização e escoamento', 'medium', 'E', 'Superfícies impermeáveis dificultam a entrada da água no solo e favorecem o escoamento superficial. A intensidade do efeito também depende de chuva, relevo e drenagem.'),
  ('d1394000-0000-4000-8000-000000000013', 'Como se denomina a área cujas águas superficiais são drenadas por um rio principal e seus afluentes para uma saída comum?', 'Bacia hidrográfica', 'Meridiano', 'Fuso horário', 'Paralelo', 'Limite de uma região política necessariamente', 'Bacia hidrográfica', 'medium', 'A', 'Uma bacia hidrográfica é uma área de drenagem integrada por um rio e seus afluentes. Seus limites acompanham divisores de águas e não precisam coincidir com fronteiras políticas.'),
  ('d1394000-0000-4000-8000-000000000014', 'Uma notícia informa que choveu em uma cidade na manhã de terça-feira. Essa informação, sozinha, descreve principalmente:', 'o clima completo da cidade durante vários séculos', 'a latitude exata da cidade', 'o bioma de todo o país', 'uma condição do tempo atmosférico naquele momento', 'a quantidade total de rios da região', 'Tempo atmosférico e clima', 'medium', 'D', 'O tempo atmosférico corresponde às condições observadas em um momento ou intervalo curto. O clima se refere a padrões e variabilidade analisados ao longo de períodos extensos; uma manhã não é suficiente para caracterizá-lo.'),
  ('d1394000-0000-4000-8000-000000000015', 'Qual bioma brasileiro é associado ao semiárido e apresenta vegetação com diversas adaptações a períodos de pouca disponibilidade de água?', 'Pampa', 'Caatinga', 'Floresta amazônica', 'Manguezal exclusivamente', 'Floresta temperada europeia', 'Caatinga', 'easy', 'B', 'A Caatinga está associada ao semiárido brasileiro. Sua vegetação apresenta diferentes adaptações às condições de disponibilidade de água, sem que todas as plantas tenham exatamente a mesma estratégia.'),
  ('d1394000-0000-4000-8000-000000000016', 'Qual bioma brasileiro, restrito ao Rio Grande do Sul, apresenta extensas formações campestres?', 'Caatinga', 'Pantanal', 'Pampa', 'Amazônia', 'Cerrado', 'Pampa', 'easy', 'C', 'O Pampa brasileiro situa-se no Rio Grande do Sul e possui formações campestres características. Campos não são necessariamente áreas sem biodiversidade ou sem relevância ambiental.'),
  ('d1394000-0000-4000-8000-000000000017', 'Considerando renovável uma fonte reposta por processos naturais em escala compatível com seu uso, qual opção é uma fonte renovável de energia?', 'Carvão mineral', 'Petróleo', 'Gás natural fóssil', 'Urânio extraído de jazidas', 'Vento usado na geração eólica', 'Fontes renováveis de energia', 'easy', 'E', 'O vento é reposto por processos atmosféricos e pode ser utilizado na geração eólica. Ser renovável não significa produzir energia continuamente nem ter impacto ambiental inexistente.'),
  ('d1394000-0000-4000-8000-000000000018', 'Um mapa apresenta a distribuição da quantidade média de chuva por áreas de uma região, usando cores e uma legenda com valores. Qual é sua finalidade principal?', 'Representar espacialmente um fenômeno específico: a distribuição da chuva.', 'Mostrar apenas nomes de governantes.', 'Substituir toda observação meteorológica futura.', 'Comprovar que todas as áreas recebem a mesma quantidade de chuva.', 'Representar necessariamente somente fronteiras internacionais.', 'Mapas temáticos', 'easy', 'A', 'Um mapa temático destaca a distribuição espacial de um fenômeno selecionado. Nesse caso, cores e legenda permitem comparar quantidades de chuva entre áreas, conforme os dados usados no mapa.')
), inserted_model as (
  insert into private.simulations(id,title,question_count,subject,published,free_access)
  values('d1395000-0000-4000-8000-000000000001','Geografia',20,'geografia',false,false)
  on conflict(id) do nothing returning id
), inserted_questions as (
  insert into public.questions(id,statement,option_a,option_b,option_c,option_d,option_e,
                               subject,topic,difficulty,target_exam,status,version)
  select id::uuid,statement,option_a,option_b,option_c,option_d,option_e,
         'geografia',topic,difficulty,'both','draft',1 from source_data
  on conflict(id) do nothing returning id
)
insert into public.question_answers(question_id,correct_answer,explanation)
select q.id,s.correct_answer,s.explanation
from inserted_questions q join source_data s on s.id::uuid=q.id;
