-- Etapa 39: Geografia; originais geradas com auxílio de IA, revisão humana pendente.
-- Gerado por scripts/build-subject-content.mjs. Uma instrução atômica por lote.
-- Conflitos de ID preservam conteúdo/modelos/gabaritos; sem reparo silencioso.
with source_data (id, statement, option_a, option_b, option_c, option_d, option_e,
                  topic, difficulty, correct_answer, explanation) as (
  values
  ('d1394000-0000-4000-8000-000000000001', 'Um ponto está localizado a 15° de latitude sul e 45° de longitude oeste. Em quais hemisférios ele se encontra?', 'Norte e Leste', 'Sul e Leste', 'Sul e Oeste', 'Norte e Oeste', 'Norte e Sul simultaneamente', 'Coordenadas e hemisférios', 'easy', 'C', 'A latitude sul indica posição ao sul da linha do Equador. A longitude oeste indica posição a oeste do meridiano de Greenwich. Portanto, o ponto fica nos hemisférios Sul e Oeste.'),
  ('d1394000-0000-4000-8000-000000000002', 'No sistema usual de coordenadas geográficas, as longitudes são medidas para leste ou oeste a partir de qual referência de 0°?', 'Trópico de Câncer', 'Círculo Polar Antártico', 'Trópico de Capricórnio', 'Linha do Equador', 'Meridiano de Greenwich', 'Meridiano de referência', 'easy', 'E', 'O meridiano de Greenwich é a referência de longitude 0°. A linha do Equador é a referência para latitude, e não para longitude.'),
  ('d1394000-0000-4000-8000-000000000003', 'Em um modelo simplificado de fusos horários, cada 15° de longitude corresponde a uma hora, com horários mais adiantados a leste. Se são 10h no meridiano de 0°, que horas são no meridiano de 30° leste nesse modelo?', '12h', '8h', '10h', '11h', '14h', 'Fusos teóricos', 'medium', 'A', 'A diferença é de 30 ÷ 15 = 2 horas. Como o ponto está a leste, somam-se duas horas: 12h. O exercício usa fusos teóricos, sem fronteiras oficiais ou horário de verão.'),
  ('d1394000-0000-4000-8000-000000000004', 'Em um mapa fictício de uso do solo, a legenda indica verde para floresta, amarelo para agricultura e cinza para área construída. O que representa uma área amarela nesse mapa?', 'Floresta', 'Área construída', 'Um rio necessariamente', 'Agricultura', 'Uma fronteira internacional necessariamente', 'Legenda cartográfica', 'easy', 'D', 'A legenda fornecida associa amarelo à agricultura. Cores e símbolos precisam ser interpretados pela legenda do mapa específico, sem supor que tenham sempre o mesmo significado em todos os mapas.'),
  ('d1394000-0000-4000-8000-000000000005', 'Um mapa representa curvas de nível, cada uma ligando pontos de mesma altitude, com intervalo de 20 m entre curvas consecutivas. Na mesma escala, em qual trecho a encosta tende a ser mais íngreme?', 'Onde as curvas estão mais afastadas.', 'Onde as curvas estão mais próximas.', 'Onde não existe mudança de altitude.', 'Onde todas as curvas têm exatamente a mesma altitude.', 'Em qualquer trecho, pois a distância entre as curvas não importa.', 'Curvas de nível', 'medium', 'B', 'Com intervalo de altitude e escala iguais, curvas próximas indicam a mesma variação vertical em menor distância horizontal. Isso corresponde a maior declividade da encosta.'),
  ('d1394000-0000-4000-8000-000000000006', 'Em um mapa de escala 1:50.000, a distância em linha reta entre dois pontos mede 4 cm. Qual é a distância real correspondente?', '20 km', '200 km', '2 km', '200 m', '20 m', 'Escala e conversão de distância', 'medium', 'C', 'A distância real é 4 × 50.000 = 200.000 cm. Como 100.000 cm correspondem a 1 km, o resultado é 2 km.'),
  ('d1394000-0000-4000-8000-000000000007', 'Um município fictício tem 90.000 habitantes distribuídos em uma área de 300 km². Usando densidade demográfica = população ÷ área, qual é sua densidade média?', '30 hab./km²', '3 hab./km²', '900 hab./km²', '3.000 hab./km²', '300 hab./km²', 'Densidade demográfica', 'medium', 'E', 'Dividindo 90.000 habitantes por 300 km², obtemos 300 hab./km². É uma média do território e não significa que cada quilômetro quadrado tenha exatamente esse número de moradores.'),
  ('d1394000-0000-4000-8000-000000000008', 'Em uma região fictícia, a proporção da população residente em áreas urbanas passou de 60% para 80% entre duas pesquisas. Qual foi o aumento, em pontos percentuais?', '20 pontos percentuais', '80 pontos percentuais', '60 pontos percentuais', '33 pontos percentuais', '140 pontos percentuais', 'Proporção da população urbana', 'medium', 'A', 'A diferença entre as proporções é 80 − 60 = 20 pontos percentuais. Esse indicador não é o mesmo que o aumento percentual relativo de aproximadamente 33,3% sobre o valor inicial.'),
  ('d1394000-0000-4000-8000-000000000009', 'Uma família muda permanentemente de uma área rural para uma cidade em busca de trabalho. Qual tipo de deslocamento está exemplificado?', 'Turismo de férias', 'Migração pendular diária', 'Viagem de retorno no mesmo dia', 'Êxodo rural', 'Deslocamento de um bairro urbano para outro', 'Êxodo rural', 'easy', 'D', 'O êxodo rural é o deslocamento de pessoas do campo para a cidade. No exemplo, há mudança de residência, e não apenas uma viagem diária ou temporária.'),
  ('d1394000-0000-4000-8000-000000000010', 'Uma pessoa mora em um município, vai diariamente a outro para trabalhar e retorna à sua residência ao fim do dia. Como esse movimento é geralmente denominado?', 'Mudança definitiva de país', 'Deslocamento pendular', 'Êxodo rural necessariamente', 'Emigração permanente', 'Turismo internacional', 'Deslocamento pendular', 'easy', 'B', 'O deslocamento pendular envolve trajetos regulares de ida e volta, como os realizados para trabalhar ou estudar. A pessoa mantém sua residência, sem mudança definitiva no exemplo.'),
  ('d1394000-0000-4000-8000-000000000011', 'Uma indústria transforma algodão em tecido. Na divisão tradicional da economia em setores primário, secundário e terciário, essa atividade industrial pertence a qual setor?', 'Primário, por envolver qualquer produto de origem vegetal.', 'Terciário, por ser necessariamente comércio varejista.', 'Secundário, por transformar matéria-prima.', 'Primário, por extrair tecido pronto da natureza.', 'Terciário, por prestar exclusivamente serviços de transporte.', 'Setores da economia', 'easy', 'C', 'A transformação industrial da matéria-prima em tecido pertence ao setor secundário. O cultivo do algodão pertence ao primário; a venda e o transporte são exemplos de atividades do terciário.'),
  ('d1394000-0000-4000-8000-000000000012', 'Uma área de solo exposto e vegetação é coberta por asfalto impermeável. Mantidas as demais condições, qual efeito tende a ocorrer durante uma chuva?', 'A água passa a infiltrar mais facilmente pelo asfalto.', 'Toda a água deixa de circular no ambiente.', 'A chuva se transforma diretamente em neve.', 'A água desaparece sem escoar ou evaporar.', 'A infiltração no trecho diminui e o escoamento superficial tende a aumentar.', 'Impermeabilização e escoamento', 'medium', 'E', 'Superfícies impermeáveis dificultam a entrada da água no solo e favorecem o escoamento superficial. A intensidade do efeito também depende de chuva, relevo e drenagem.'),
  ('d1394000-0000-4000-8000-000000000013', 'Como se denomina a área cujas águas superficiais são drenadas por um rio principal e seus afluentes para uma saída comum?', 'Bacia hidrográfica', 'Meridiano', 'Fuso horário', 'Paralelo', 'Limite de uma região política necessariamente', 'Bacia hidrográfica', 'medium', 'A', 'Uma bacia hidrográfica é uma área de drenagem integrada por um rio e seus afluentes. Seus limites acompanham divisores de águas e não precisam coincidir com fronteiras políticas.'),
  ('d1394000-0000-4000-8000-000000000014', 'Uma notícia informa que choveu em uma cidade na manhã de terça-feira. Essa informação, sozinha, descreve principalmente:', 'o clima completo da cidade durante vários séculos', 'a latitude exata da cidade', 'o bioma de todo o país', 'uma condição do tempo atmosférico naquele momento', 'a quantidade total de rios da região', 'Tempo atmosférico e clima', 'medium', 'D', 'O tempo atmosférico corresponde às condições observadas em um momento ou intervalo curto. O clima se refere a padrões e variabilidade analisados ao longo de períodos extensos; uma manhã não é suficiente para caracterizá-lo.'),
  ('d1394000-0000-4000-8000-000000000015', 'Qual bioma brasileiro é associado ao semiárido e apresenta vegetação com diversas adaptações a períodos de pouca disponibilidade de água?', 'Pampa', 'Caatinga', 'Floresta amazônica', 'Manguezal exclusivamente', 'Floresta temperada europeia', 'Caatinga', 'easy', 'B', 'A Caatinga está associada ao semiárido brasileiro. Sua vegetação apresenta diferentes adaptações às condições de disponibilidade de água, sem que todas as plantas tenham exatamente a mesma estratégia.'),
  ('d1394000-0000-4000-8000-000000000016', 'Qual bioma brasileiro, restrito ao Rio Grande do Sul, apresenta extensas formações campestres?', 'Caatinga', 'Pantanal', 'Pampa', 'Amazônia', 'Cerrado', 'Pampa', 'easy', 'C', 'O Pampa brasileiro situa-se no Rio Grande do Sul e possui formações campestres características. Campos não são necessariamente áreas sem biodiversidade ou sem relevância ambiental.'),
  ('d1394000-0000-4000-8000-000000000017', 'Considerando renovável uma fonte reposta por processos naturais em escala compatível com seu uso, qual opção é uma fonte renovável de energia?', 'Carvão mineral', 'Petróleo', 'Gás natural fóssil', 'Urânio extraído de jazidas', 'Vento usado na geração eólica', 'Fontes renováveis de energia', 'easy', 'E', 'O vento é reposto por processos atmosféricos e pode ser utilizado na geração eólica. Ser renovável não significa produzir energia continuamente nem ter impacto ambiental inexistente.'),
  ('d1394000-0000-4000-8000-000000000018', 'Um mapa apresenta a distribuição da quantidade média de chuva por áreas de uma região, usando cores e uma legenda com valores. Qual é sua finalidade principal?', 'Representar espacialmente um fenômeno específico: a distribuição da chuva.', 'Mostrar apenas nomes de governantes.', 'Substituir toda observação meteorológica futura.', 'Comprovar que todas as áreas recebem a mesma quantidade de chuva.', 'Representar necessariamente somente fronteiras internacionais.', 'Mapas temáticos', 'easy', 'A', 'Um mapa temático destaca a distribuição espacial de um fenômeno selecionado. Nesse caso, cores e legenda permitem comparar quantidades de chuva entre áreas, conforme os dados usados no mapa.')
), inserted_model as (
  insert into private.simulations(id,title,question_count,subject,published,free_access)
  values('d1395000-0000-4000-8000-000000000001','Geografia',20,'geografia',false,false)
  on conflict(id) do nothing returning id
), inserted_questions as (
  insert into public.questions(id,statement,option_a,option_b,option_c,option_d,option_e,
                               subject,topic,difficulty,target_exam,status,version)
  select id::uuid,statement,option_a,option_b,option_c,option_d,option_e,
         'geografia',topic,difficulty,'both','draft',1 from source_data
  on conflict(id) do nothing returning id
)
insert into public.question_answers(question_id,correct_answer,explanation)
select q.id,s.correct_answer,s.explanation
from inserted_questions q join source_data s on s.id::uuid=q.id;
