-- Etapa 39: História; originais geradas com auxílio de IA, revisão humana pendente.
-- Gerado por scripts/build-subject-content.mjs. Uma instrução atômica por lote.
-- Conflitos de ID preservam conteúdo/modelos/gabaritos; sem reparo silencioso.
with source_data (id, statement, option_a, option_b, option_c, option_d, option_e,
                  topic, difficulty, correct_answer, explanation) as (
  values
  ('d1392000-0000-4000-8000-000000000001', 'Em uma pesquisa sobre a história de um bairro, estudantes gravam entrevistas com antigos moradores. Que tipo de fonte é produzido principalmente por essas entrevistas?', 'Fonte cartográfica', 'Fonte oral', 'Fonte arqueológica sem linguagem', 'Fonte mineral', 'Fonte exclusivamente numérica', 'Fontes orais', 'easy', 'B', 'Entrevistas registram relatos falados e constituem fontes orais. Esses relatos apresentam memórias e perspectivas que devem ser contextualizadas e comparadas com outros registros.'),
  ('d1392000-0000-4000-8000-000000000002', 'Em um exercício hipotético, uma fotografia de uma praça mostra poucas pessoas em certo instante de 1930. Qual conclusão é adequada para uma análise histórica dessa imagem?', 'Ninguém morava na cidade naquele ano.', 'Todas as praças do país eram iguais.', 'A fotografia registra todos os acontecimentos de 1930.', 'A imagem mostra um recorte que deve ser relacionado a outras fontes.', 'Nenhuma fotografia pode ser usada como fonte.', 'Leitura de fotografias', 'medium', 'D', 'Uma fotografia registra um recorte de tempo e espaço, com enquadramento e condições de produção. Ela é uma fonte útil, mas não representa automaticamente toda a cidade ou todo o ano.'),
  ('d1392000-0000-4000-8000-000000000003', 'Dois jornais de uma mesma época descrevem um conflito de maneiras diferentes. Qual procedimento ajuda a investigar historicamente essa diferença?', 'Aceitar sempre o jornal com mais páginas.', 'Descartar ambos apenas por discordarem.', 'Examinar autoria, público, contexto e outras evidências.', 'Escolher a versão mais agradável ao pesquisador.', 'Supor que nenhum jornal tem posição editorial.', 'Crítica das fontes', 'medium', 'C', 'A análise considera quem produziu cada relato, para qual público e em quais circunstâncias, além da comparação com outras fontes. A discordância pode revelar perspectivas e interesses distintos.'),
  ('d1392000-0000-4000-8000-000000000004', 'Na contagem convencional dos séculos da era comum, a que século pertence o ano de 1750?', 'Século XVIII', 'Século XVII', 'Século XVI', 'Século XIX', 'Século XX', 'Séculos', 'easy', 'A', 'O século XVIII corresponde aos anos de 1701 a 1800. Como 1750 está nesse intervalo, pertence ao século XVIII.'),
  ('d1392000-0000-4000-8000-000000000005', 'Considere os marcos e anos: I. Proclamação da República, 1889. II. Abertura dos portos às nações amigas, 1808. III. Lei Áurea, 1888. Qual ordem apresenta os marcos do mais antigo ao mais recente?', 'I – II – III', 'III – I – II', 'II – I – III', 'I – III – II', 'II – III – I', 'Ordenação cronológica', 'easy', 'E', 'Ordenando os anos em ordem crescente, temos 1808, 1888 e 1889. Portanto, a sequência é abertura dos portos, Lei Áurea e Proclamação da República: II, III e I.'),
  ('d1392000-0000-4000-8000-000000000006', 'A abertura dos portos às nações amigas, em 1808, alterou uma regra importante do comércio colonial. Qual mudança está relacionada a essa medida?', 'Proibição de qualquer comércio marítimo.', 'Permissão de comércio com nações amigas de Portugal.', 'Abolição imediata da escravidão em todo o Brasil.', 'Criação da República brasileira.', 'Proibição de entrada da corte portuguesa no Brasil.', 'Abertura dos portos', 'medium', 'B', 'A medida permitiu comércio com nações amigas de Portugal e rompeu a exclusividade comercial metropolitana. Não significou abolição da escravidão ou implantação de uma república.'),
  ('d1392000-0000-4000-8000-000000000007', 'Qual acontecimento ajuda a explicar o contexto da transferência da corte portuguesa para o Brasil em 1808?', 'A construção de Brasília.', 'A Proclamação da República no Brasil.', 'O fim da Segunda Guerra Mundial.', 'As guerras napoleônicas e a invasão de Portugal.', 'A assinatura da Lei Áurea.', 'Transferência da corte', 'medium', 'D', 'A ameaça e a invasão de Portugal no contexto das guerras napoleônicas contribuíram para a transferência da corte. Os demais acontecimentos pertencem a períodos posteriores.'),
  ('d1392000-0000-4000-8000-000000000008', 'Qual foi a determinação central da Lei Áurea, de 13 de maio de 1888?', 'Criar o regime republicano.', 'Instituir o voto universal.', 'Extinguir legalmente a escravidão no Brasil.', 'Proibir a entrada de qualquer mercadoria estrangeira.', 'Transferir a capital para Brasília.', 'Abolição legal da escravidão', 'easy', 'C', 'A Lei Áurea determinou a extinção da escravidão no Brasil. Esse conteúdo legal não deve ser confundido com a eliminação imediata de todas as desigualdades ou com a criação da República.'),
  ('d1392000-0000-4000-8000-000000000009', 'A Lei do Ventre Livre, de 1871, declarou de condição livre os filhos de mulheres escravizadas nascidos a partir de sua data. Qual afirmação interpreta essa medida sem ampliar indevidamente seu alcance?', 'A regra sobre os nascimentos não libertava automaticamente todas as pessoas adultas escravizadas.', 'Toda a escravidão brasileira terminou imediatamente em 1871.', 'A lei criou a República brasileira.', 'A lei passou a proibir todos os nascimentos no país.', 'A medida concedeu terra a toda pessoa nascida antes de 1871.', 'Lei do Ventre Livre', 'medium', 'A', 'A disposição sobre os filhos nascidos a partir da lei não equivalia à abolição geral. A própria lei estabelecia condições de criação e de utilização de serviços desses menores, limitando a liberdade prática.'),
  ('d1392000-0000-4000-8000-000000000010', 'Qual transformação política está associada à Proclamação da República no Brasil, em 15 de novembro de 1889?', 'Retorno do Brasil à condição de colônia portuguesa.', 'Criação do primeiro governo monárquico brasileiro.', 'Abolição da escravidão pela Lei do Ventre Livre.', 'Transferência da corte portuguesa para o Brasil.', 'Fim da monarquia e implantação de um regime republicano.', 'Proclamação da República', 'easy', 'E', 'A Proclamação da República encerrou a monarquia e foi seguida por um governo provisório republicano. Essa mudança de regime não significou participação eleitoral de toda a população.'),
  ('d1392000-0000-4000-8000-000000000011', 'Segundo o artigo 70 da Constituição brasileira de 1891, os analfabetos não podiam se alistar como eleitores. O que essa restrição permite concluir sobre aquele sistema eleitoral?', 'Todos os habitantes tinham acesso ao voto.', 'A participação eleitoral possuía exclusões legais.', 'Somente crianças eram eleitores.', 'Não existia qualquer regra de alistamento.', 'A restrição referia-se apenas a visitantes estrangeiros.', 'Limites do voto em 1891', 'medium', 'B', 'A exclusão dos analfabetos mostra que a participação eleitoral não abrangia toda a população. A questão trata da regra histórica de 1891, e não das regras eleitorais atuais.'),
  ('d1392000-0000-4000-8000-000000000012', 'Nos artigos iniciais da Constituição de 1891, as antigas províncias passam a formar estados unidos em uma República Federativa. Que organização política está indicada nessa estrutura?', 'A extinção de qualquer governo nacional.', 'A transformação de cada estado em colônia estrangeira.', 'A criação de uma única cidade sem divisões territoriais.', 'A união de estados em uma federação.', 'O retorno ao regime de capitanias hereditárias.', 'Federalismo na Constituição de 1891', 'medium', 'D', 'A federação reúne estados em uma organização nacional. Os artigos 1º e 2º da Constituição de 1891 expressam a união e a transformação das antigas províncias em estados.'),
  ('d1392000-0000-4000-8000-000000000013', 'No contexto da Revolução Francesa, o artigo 1º da Declaração dos Direitos do Homem e do Cidadão, de 1789, apresenta qual princípio?', 'Privilégios jurídicos determinados exclusivamente pelo nascimento.', 'Submissão de todo cidadão a um senhor feudal.', 'Liberdade e igualdade em direitos.', 'Proibição de expressar qualquer opinião.', 'Obrigatoriedade de uma única profissão para todos.', 'Declaração de direitos de 1789', 'medium', 'C', 'O artigo afirma a liberdade e a igualdade em direitos. Enunciar esse princípio não comprova que ele tenha sido aplicado imediatamente a todas as pessoas ou em todas as situações.'),
  ('d1392000-0000-4000-8000-000000000014', 'Uma tabuleta cuneiforme da antiga Mesopotâmia registra a distribuição de utensílios de cobre. O que esse uso da escrita permite compreender?', 'A escrita também podia registrar a circulação e a administração de bens.', 'A escrita servia exclusivamente para poesias.', 'Não existia qualquer controle de bens.', 'Utensílios de cobre eram inventados no século XX.', 'Todos os habitantes sabiam ler necessariamente.', 'Escrita e administração na Mesopotâmia', 'medium', 'A', 'Registros de distribuição de bens mostram usos administrativos e econômicos da escrita. A existência de uma tabuleta não implica alfabetização de toda a população.'),
  ('d1392000-0000-4000-8000-000000000015', 'Em um exemplo didático de organização fabril, um grupo corta o tecido, outro costura e um terceiro embala as peças. Qual característica da produção é descrita?', 'Ausência de qualquer organização do trabalho.', 'Produção de alimentos por coleta silvestre.', 'Fim de todas as etapas de fabricação.', 'Cada trabalhador produz sozinho todas as peças do início ao fim.', 'Divisão de tarefas entre trabalhadores.', 'Divisão de tarefas na produção', 'easy', 'E', 'As etapas são distribuídas entre grupos, caracterizando divisão de tarefas. O exemplo não afirma que toda fábrica tenha exatamente essa organização ou que cada trabalhador realize o processo completo.'),
  ('d1392000-0000-4000-8000-000000000016', 'Ao estudar a história dos povos indígenas no Brasil, qual abordagem evita tratá-los como um único grupo cultural?', 'Afirmar que todos sempre falaram a mesma língua.', 'Reconhecer diferentes povos, línguas e formas de organização.', 'Negar a existência de mudanças históricas entre esses povos.', 'Considerar que suas histórias começaram apenas com registros europeus.', 'Supor que todos vivem de modo idêntico em qualquer lugar.', 'Diversidade dos povos indígenas', 'easy', 'B', 'Existem diversos povos indígenas, com línguas, trajetórias e formas de organização próprias. Estudar essa diversidade evita generalizações e reconhece seus sujeitos e processos históricos.'),
  ('d1392000-0000-4000-8000-000000000017', 'Em uma comparação hipotética, fotografias de 1950 e 2020 mostram a mesma estação ferroviária: o edifício permanece, mas a praça ao redor passou a ter novas vias. Qual leitura histórica considera as duas observações?', 'Nada mudou entre as duas datas.', 'Nenhum elemento permaneceu.', 'A imagem de 2020 prova como a praça era em todos os séculos.', 'Há permanência do edifício e transformação de parte de seu entorno.', 'As fotografias demonstram que os dois anos são o mesmo momento.', 'Mudanças e permanências', 'medium', 'D', 'A comparação identifica um elemento que permanece e outro que se transforma. Mudanças e permanências podem coexistir; os registros não mostram todos os acontecimentos do intervalo.'),
  ('d1392000-0000-4000-8000-000000000018', 'Qual exemplo se relaciona principalmente à dimensão imaterial do patrimônio cultural?', 'O concreto de uma ponte.', 'As paredes físicas de um edifício.', 'Saberes e modos de fazer transmitidos por uma comunidade.', 'Um terreno considerado apenas por sua área em metros quadrados.', 'A massa de uma pedra sem relação com uma prática cultural.', 'Patrimônio cultural imaterial', 'medium', 'C', 'Saberes, modos de fazer e práticas transmitidas por comunidades integram a dimensão imaterial do patrimônio. Isso não significa que toda prática esteja automaticamente registrada como bem cultural oficial.')
), inserted_model as (
  insert into private.simulations(id,title,question_count,subject,published,free_access)
  values('d1393000-0000-4000-8000-000000000001','História',20,'historia',false,false)
  on conflict(id) do nothing returning id
), inserted_questions as (
  insert into public.questions(id,statement,option_a,option_b,option_c,option_d,option_e,
                               subject,topic,difficulty,target_exam,status,version)
  select id::uuid,statement,option_a,option_b,option_c,option_d,option_e,
         'historia',topic,difficulty,'both','draft',1 from source_data
  on conflict(id) do nothing returning id
)
insert into public.question_answers(question_id,correct_answer,explanation)
select q.id,s.correct_answer,s.explanation
from inserted_questions q join source_data s on s.id::uuid=q.id;
