-- Etapa 38: 18 questões originais de Português; geradas com auxílio de IA.
-- Revisão humana pendente. Gerado por scripts/build-portuguese-content.mjs.
-- Fonte atual: revisão da etapa 41, versão 2; INSERT não atualiza linhas existentes.
-- Apenas INSERT atômico em draft; reexecução preserva conteúdo, status e gabaritos.
-- Não reparar um gabarito de questão existente silenciosamente.
with source_data (id, statement, option_a, option_b, option_c, option_d, option_e,
                  topic, difficulty, correct_answer, explanation) as (
  values
  ('d1380000-0000-4000-8000-000000000001', 'Leia: “A biblioteca do bairro funciona de terça a sábado, das 9h às 17h. Às quartas-feiras, recebe livros doados até as 15h.” Segundo o aviso, em qual dia a biblioteca recebe doações de livros?', 'Segunda-feira', 'Terça-feira', 'Domingo', 'Quarta-feira', 'Sábado', 'Informação explícita', 'easy', 'D', 'O aviso informa expressamente que as doações são recebidas às quartas-feiras. Os dias gerais de funcionamento não devem ser confundidos com o dia indicado para receber livros doados.'),
  ('d1380000-0000-4000-8000-000000000002', 'Leia: “Ao chegar à sala, Luana viu Pedro fechar um guarda-chuva com gotas de água. Ele deixou o objeto aberto perto da porta para secar e comentou: ‘Ainda bem que trouxe isto hoje.’” Qual inferência é mais bem sustentada pelas pistas do trecho?', 'Pedro tinha ido à sala para lavar o guarda-chuva.', 'Luana havia emprestado o guarda-chuva a Pedro.', 'Pedro deixou o guarda-chuva para Luana usar na volta para casa.', 'Pedro havia deixado o guarda-chuva na sala desde o dia anterior.', 'Pedro provavelmente enfrentou chuva antes de chegar à sala.', 'Inferência textual', 'medium', 'E', 'As gotas, a necessidade de secar o guarda-chuva e o comentário de Pedro tornam provável que ele tenha usado o objeto para se proteger da chuva antes de chegar. Essa é uma inferência apoiada nas pistas, não uma certeza expressamente declarada. As demais alternativas acrescentam acontecimentos ou intenções sem apoio no trecho.'),
  ('d1380000-0000-4000-8000-000000000003', 'Leia: “No recreio, estudantes separaram cascas de frutas e folhas secas. O material foi levado à composteira da escola e, semanas depois, ajudou a adubar a horta.” Qual é o tema central do trecho?', 'O transporte de estudantes até a escola.', 'O aproveitamento de resíduos orgânicos na escola.', 'A construção de novas salas de aula.', 'A venda de frutas no comércio do bairro.', 'A mudança do horário do recreio.', 'Tema central', 'easy', 'B', 'O trecho acompanha o uso de cascas e folhas na compostagem e sua aplicação na horta. Essa sequência trata do aproveitamento de resíduos orgânicos; os outros assuntos não são desenvolvidos.'),
  ('d1380000-0000-4000-8000-000000000004', 'Leia o aviso: “Devido à manutenção, a quadra permanecerá fechada nesta sexta-feira. As atividades esportivas ocorrerão no pátio.” Qual é a finalidade principal desse aviso?', 'Convencer os estudantes a comprar equipamentos.', 'Informar uma alteração no local das atividades.', 'Narrar uma competição que já terminou.', 'Ensinar as regras de um esporte.', 'Avaliar o desempenho dos atletas.', 'Finalidade de um aviso', 'easy', 'B', 'O aviso comunica que a quadra estará fechada e indica o pátio como local das atividades. Sua finalidade principal é informar essa alteração, não narrar, vender, ensinar regras ou avaliar atletas.'),
  ('d1380000-0000-4000-8000-000000000005', 'Leia: “A turma mudou a apresentação para a sala porque começou a chover.” A parte iniciada por “porque” apresenta:', 'uma condição para chover', 'uma oposição à mudança de local', 'uma finalidade da apresentação', 'a causa da mudança de local', 'uma comparação entre duas salas', 'Relação de causa', 'easy', 'D', 'O início da chuva explica por que a apresentação foi transferida. Nesse contexto, a oração introduzida por “porque” apresenta a causa da mudança.'),
  ('d1380000-0000-4000-8000-000000000006', 'Leia: “O ônibus chegou depois do horário previsto; por isso, a visita começou mais tarde.” A expressão “por isso” estabelece, nesse contexto, uma relação de:', 'concessão', 'alternância', 'condição', 'consequência', 'comparação', 'Relação de consequência', 'easy', 'D', 'A visita ter começado mais tarde é apresentada como consequência do atraso do ônibus. A expressão “por isso” conecta o atraso a esse resultado.'),
  ('d1380000-0000-4000-8000-000000000007', 'Leia: “Se o tempo estiver firme, faremos a atividade no jardim.” A palavra “se” introduz:', 'uma comparação com outro jardim', 'uma oposição ao tempo firme', 'a conclusão de uma atividade passada', 'a causa comprovada da atividade', 'uma condição para realizar a atividade no jardim', 'Relação de condição', 'easy', 'E', 'A realização da atividade no jardim depende da condição de o tempo estar firme. O enunciado não afirma que essa condição já se cumpriu.'),
  ('d1380000-0000-4000-8000-000000000008', 'Leia: “Embora estivesse cansada, Marina terminou a leitura.” A palavra “embora” introduz uma circunstância que:', 'mostra que Marina não terminou a leitura', 'poderia dificultar a ação, mas não impediu sua realização', 'garante que a leitura será feita no futuro', 'é apresentada como finalidade da leitura', 'compara dois livros de mesmo tamanho', 'Relação de concessão', 'medium', 'B', 'O cansaço poderia dificultar a leitura, mas Marina a terminou. Essa relação de concessão apresenta uma circunstância contrária à expectativa sem impedir a ação da oração principal.'),
  ('d1380000-0000-4000-8000-000000000009', 'Leia: “Os cartazes foram entregues à professora. Ela os colocou no mural.” No segundo período, o pronome “os” retoma:', 'os cartazes', 'o mural', 'a entrega', 'os estudantes', 'a professora', 'Referência pronominal', 'easy', 'A', 'O pronome “os” retoma “os cartazes”, que foram colocados no mural. Já “Ela” retoma a professora. Os estudantes não são mencionados no trecho.'),
  ('d1380000-0000-4000-8000-000000000010', 'Leia: “O laboratório recebeu um microscópio novo. O aparelho será usado nas aulas de Ciências.” Qual expressão do segundo período retoma o microscópio mencionado no primeiro?', 'O aparelho', 'O laboratório', 'será usado', 'de Ciências', 'nas aulas', 'Coesão por substituição', 'medium', 'A', 'A expressão “O aparelho” retoma o microscópio por uma denominação mais geral. Essa substituição mantém a referência e evita repetir o nome do equipamento.'),
  ('d1380000-0000-4000-8000-000000000011', 'Leia: “Durante a reunião, ninguém falava. Uma pergunta de Joana quebrou o silêncio.” Nesse contexto, “quebrou o silêncio” significa que a pergunta:', 'impediu Joana de falar', 'encerrou definitivamente a reunião', 'interrompeu a ausência de fala', 'foi feita sem produzir som', 'danificou um objeto da sala', 'Sentido figurado', 'medium', 'C', '“Quebrar o silêncio” tem sentido figurado: interromper um período em que ninguém fala. O trecho não descreve a quebra física de um objeto.'),
  ('d1380000-0000-4000-8000-000000000012', 'Qual frase expressa uma opinião, marcada por uma avaliação pessoal?', 'A sala tem vinte cadeiras.', 'A oficina começou às 14h.', 'A exposição é a mais interessante da cidade.', 'O formulário pede nome e telefone.', 'A exposição ocupa duas salas.', 'Fato e opinião', 'medium', 'C', 'Chamar a exposição de “a mais interessante” expressa um julgamento de valor. As demais frases apresentam informações que podem ser verificadas, embora sua veracidade dependa de conferência.'),
  ('d1380000-0000-4000-8000-000000000013', 'Leia: “Rafael, guarde os livros na estante.” Qual é a função da vírgula nessa frase?', 'Separar o nome da pessoa a quem a ordem é dirigida.', 'Indicar a omissão da palavra “livros”.', 'Marcar o término de uma pergunta.', 'Separar o sujeito de seu predicado.', 'Indicar uma lista de três objetos.', 'Pontuação e vocativo', 'medium', 'A', '“Rafael” funciona como vocativo, pois chama a pessoa a quem se dirige a ordem. A vírgula separa esse chamamento do restante da frase. Não se trata de separar sujeito e predicado.'),
  ('d1380000-0000-4000-8000-000000000014', 'Leia a frase isolada: “Paula avisou a Renata que sua inscrição estava confirmada.” Sem informações adicionais, por que a expressão “sua inscrição” pode ser ambígua?', 'Porque a palavra “inscrição” é um verbo.', 'Porque Paula e Renata são necessariamente a mesma pessoa.', 'Porque não se sabe se a inscrição foi confirmada.', 'Porque a frase informa duas datas diferentes.', 'Porque pode se referir à inscrição de Paula ou à de Renata.', 'Ambiguidade referencial', 'medium', 'E', 'O possessivo “sua”, sem contexto adicional, permite associar a inscrição a Paula ou a Renata. Nomear a pessoa responsável pela inscrição elimina essa dúvida de referência.'),
  ('d1380000-0000-4000-8000-000000000015', 'Qual frase apresenta concordância entre o sujeito e o verbo de acordo com a norma-padrão?', 'As alunas chegaram cedo.', 'As alunas chega cedo.', 'As alunas chegou cedo.', 'As alunas cheguei cedo.', 'As alunas chegamos cedo.', 'Concordância verbal', 'medium', 'A', '“As alunas” é um sujeito na terceira pessoa do plural. A forma verbal “chegaram” concorda com essa pessoa e esse número; as demais formas não concordam com o sujeito apresentado.'),
  ('d1380000-0000-4000-8000-000000000016', 'Leia: “Amanhã visitaremos o museu com a turma.” A forma verbal “visitaremos” apresenta a visita como uma ação:', 'prevista para depois do momento da fala', 'que ocorre enquanto a frase é dita', 'habitual no passado', 'cujo sujeito não pode ser identificado', 'concluída antes do momento da fala', 'Tempo verbal em contexto', 'easy', 'A', '“Visitaremos” está no futuro do presente e indica uma ação posterior ao momento da fala. O advérbio “amanhã” reforça essa localização temporal.'),
  ('d1380000-0000-4000-8000-000000000017', 'Considere as instruções: I. Depois de preencher o formulário, confira os dados. II. Por fim, envie o formulário conferido. III. Primeiro, preencha o formulário. Qual ordem organiza essas instruções de maneira coerente?', 'III – I – II', 'I – II – III', 'I – III – II', 'II – III – I', 'III – II – I', 'Ordenação de instruções', 'easy', 'A', 'A sequência é preencher, conferir e enviar. Os marcadores “Primeiro”, “Depois de preencher” e “Por fim” indicam, respectivamente, III, I e II.'),
  ('d1380000-0000-4000-8000-000000000018', 'Leia: “Como o tempo para a tarefa era escasso, o grupo definiu prioridades.” Qual palavra pode substituir “escasso” nesse contexto, preservando o sentido?', 'infinito', 'abundante', 'limitado', 'inesgotável', 'prolongado', 'Vocabulário em contexto', 'medium', 'C', '“Escasso” indica pouca disponibilidade de tempo. “Limitado” preserva esse sentido no contexto; as outras opções sugerem tempo amplo ou longo.')
), inserted_model as (
  insert into private.simulations (id,title,question_count,subject,published,free_access)
  values ('d1381000-0000-4000-8000-000000000001','Português',20,'portugues',false,false)
  on conflict (id) do nothing
  returning id
), inserted_questions as (
  insert into public.questions (id, statement, option_a, option_b, option_c, option_d, option_e,
                               subject, topic, difficulty, target_exam, status, version)
  select id::uuid, statement, option_a, option_b, option_c, option_d, option_e,
         'portugues', topic, difficulty, 'both', 'draft', 2 from source_data
  on conflict (id) do nothing
  returning id
)
insert into public.question_answers (question_id, correct_answer, explanation)
select q.id, s.correct_answer, s.explanation
from inserted_questions q join source_data s on s.id::uuid = q.id;
